alias cointop='flatpak run com.github.miguelmota.Cointop'
alias audio-reset='~/Software/Test-Scripts/audio-reset.sh'
alias myip='curl -s https://icanhazip.com'
alias ipb='ip -br -c a'
alias bat='batcat'
